spring:
  banner:
    location: banner-dev.txt
  rabbitmq:
    # 同样配置集群地址
    addresses: rocky11:5672,rocky11:5673,rocky11:5674
    username: rabbitMQAdmin
    password: rabbitMQCipher
    # 生产者重试机制。如果刚好遇到 Leader 切换时的网络波动，它会自动重试
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3

logging:
  level:
    com.neon.niloweb.mapper: debug # 便于查看实际的SQL

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.neon.niloweb.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

snowflake:
  datacenterId: 0
  workerId: 0

system:
  video-max-size: 1000

project:
  folder: E:\IdeaProjects\nilo-parent
  pageSize: 10
