# 照抄线上的 Canal 实例配置（实例名 es-canal），只换了账号密码
canal.instance.master.address=mysql:3306
canal.instance.gtidon=false
canal.instance.dbUsername=canal
canal.instance.dbPassword=nilo-it-canal
canal.instance.connectionCharset=UTF-8
canal.instance.enableDruid=false
# 只订阅视频表与分P表
canal.instance.filter.regex=nilo\.video_info,nilo\.video_info_file
canal.instance.filter.black.regex=
