server:
  port: 7073

spring:
  application:
    name: nilo-storage
  banner:
    location: banner-dev.txt # 服务器在 nacos 里覆盖成 banner-prod.txt
  config:
    import:
      - nacos:nilo-common.yaml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:}
      password: ${NACOS_PASSWORD:}
      discovery:
        namespace: ${NACOS_NAMESPACE}
      config:
        namespace: ${NACOS_NAMESPACE}
        import-check:
          enabled: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
